// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEIFADisadvantage.DataContexts;

namespace SEIFADisadvantage.Migrations
{
    [DbContext(typeof(SeifaInfoDbContext))]
    [Migration("20180917045904_InitialCreateMigrations")]
    partial class InitialCreateMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SEIFADisadvantage.Models._2011.SeifaInfo2011", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdvantageDisadvantage");

                    b.Property<int>("Disadvantage");

                    b.Property<string>("Place");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.ToTable("Data2011");
                });

            modelBuilder.Entity("SEIFADisadvantage.Models._2016.SeifaInfo2016", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdvantageAndDisadvantageDecile");

                    b.Property<int>("AdvantageAndDisadvantageScore");

                    b.Property<int>("DisadvantageDecile");

                    b.Property<int>("DisadvantageScore");

                    b.Property<int>("EconomicResourcesDecile");

                    b.Property<int>("EconomicResourcesScore");

                    b.Property<int>("EducationAndOccupationDecile");

                    b.Property<int>("EducationAndOccupationScore");

                    b.Property<int>("LgaCode");

                    b.Property<string>("Place");

                    b.Property<int>("Population");

                    b.HasKey("Id");

                    b.ToTable("Data2016");
                });
#pragma warning restore 612, 618
        }
    }
}
